services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "${BACKEND_PORT}:8080"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - ecommerce-network
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: ecommerce-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local