services:
  postgres-goreact_ecommerce:
    image: postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  pgdata:
    name: pgdata-goreact_ecommerce